### ISSUE TITLE
Not using Monotone chain algorithm

### ISSUE THREAD

**Issue by frodrigo** [Turfjs/turf-concave#8]
Unlike the doc this package not use Monotone chain algorithm but TIN (Triangulated irregular network)

**Comment by tcql** [comment]
@frodrigo thanks, looks like a copy paste error when we first put together concave (convex does in fact use monotone chains, via [convex-hull](https://www.npmjs.com/package/convex-hull)

**Comment by tcql** [comment]
Corrected in d6270f2
